name: Electron Auto Build


on:
  push:
    # 后面改成标签推送触发打包
    # tags:
    #   - 'v*.*.*'


jobs:
  release:
    name: Build and Release

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    # 第一步：检出（下载）仓库
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 第二步：安装 NodeJS
    - name: Install Node.js
      uses: actions/setup-node@v4

    # 第三步：下载依赖
    - name: Install Dependencies
      run: |
        npm install

    # 第四步：构建 Electron
    - name: Build
      run: |
        gcc -fPIC -shared "./module-bin/main.c" -o "./pre-build/setBottom.dll"
        npm run build-Vite
        npm run build-Electron
